### ISSUE TITLE
Revise data structure for departments

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#207]
The structure of the [departments config file](https://github.com/ndlib/curate_nd/blob/master/config/departments.yml) contains a duplicate value.
```yaml
architecture:
  key: "architecture"
  identifier: "Architecture"
  selectable: true
```
The ```key``` attribute is redundant and should be refactored away.

This caused issue #205 (because @danhorst didn’t understand the implications of just changing the value).

NOTE: this may not be worth doing if the list of organizations is replaced by [locabulary](https://github.com/ndlib/locabulary).
